CREATE DATABASE HROADS_TARDE;

GO

USE HROADS_TARDE;

GO
---DDL

CREATE TABLE CLASSE(
idClasse INT PRIMARY KEY IDENTITY,
TipoClasse VARCHAR (150) NOT NULL
);
GO

CREATE TABLE TIPOHABILIDADE(
idTipoHabilidade INT PRIMARY KEY IDENTITY,
QualTipoHabilidade VARCHAR (200) NOT NULL
);
GO

CREATE TABLE HABILIDADE(
idHabilidade INT PRIMARY KEY IDENTITY,
idTipoHabilidade INT FOREIGN KEY REFERENCES TIPOHABILIDADE (idTipoHabilidade),
nome VARCHAR (200) NOT NULL
);
GO


CREATE TABLE CLASSEHABILIDADE(
idClasseHabilidade INT PRIMARY KEY IDENTITY,
idClasse INT FOREIGN KEY REFERENCES CLASSE (idClasse),
idHabilidade INT FOREIGN KEY REFERENCES HABILIDADE (idHabilidade)
);
GO

CREATE TABLE PERSONAGEM(
idPersonagem INT PRIMARY KEY IDENTITY,
idClasse INT FOREIGN KEY REFERENCES CLASSE (idClasse),
nomePersonagem VARCHAR (200) NOT NULL,
CapaMaxVida INT  NOT  NULL , 
CapaMaxMana INT  NOT  NULL , 
DataAtual DATE  NOT  NULL , 
DataCriacao DATE  NOT  NULL 
);
GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario INT PRIMARY KEY IDENTITY,
permissao VARCHAR (200) NOT NULL
);
GO

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY,
email VARCHAR (150) NOT NULL,
senha VARCHAR (100) NOT NULL,
idTipoUsuario INT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoUsuario)
);
GO